version: '3.9'
services:
  db:
    container_name: mysql
    image: 'mysql:latest'
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: blog
      #      MYSQL_USER: root
      MYSQL_PASSWORD: p@123456
      MYSQL_ROOT_PASSWORD: p@123456
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - multi-tenancy

# Volumes
volumes:
  db-data:

networks:
  multi-tenancy:
