server:
  port: 8081

spring:
  mvc:
    servlet:
      path: /api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    #    password: p@123456
    password: root
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never

db:
  configurations:
    en:
      url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    fr:
      url: jdbc:mysql://localhost:3306/blog_fr?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: root

springdoc:
  packagesToScan: com.hendisantika.multitenancy
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
